class Mobile_class():
    def __init__(self):
        print("Mobile object is created")
E1 = Mobile_class()
E2 = Mobile_class()
E3 = Mobile_class()
E4 = Mobile_class()
E5 = Mobile_class()
E6 = Mobile_class()
E7 = Mobile_class()
E8 = Mobile_class()
E9 = Mobile_class()
E10 = Mobile_class()
print(f"address: {id(E1)},Type: {type(E1)}")
print(f"address: {id(E2)},Type: {type(E2)}")
print(f"address: {id(E3)},Type: {type(E3)}")
print(f"address: {id(E4)},Type: {type(E4)}")
print(f"address: {id(E5)},Type: {type(E5)}")
print(f"address: {id(E6)},Type: {type(E6)}")
print(f"address: {id(E7)},Type: {type(E7)}")
print(f"address: {id(E8)},Type: {type(E8)}")
print(f"address: {id(E9)},Type: {type(E9)}")
print(f"address: {id(E10)},Type: {type(E10)}")